/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Error executing job with overrides: []
Traceback (most recent call last):
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/configuration_utils.py", line 705, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/configuration_utils.py", line 800, in _dict_from_json_file
    text = reader.read()
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/data/sls/scratch/nmorgan/LOGIC/model_editing/malmen/main.py", line 27, in main
    model = make_model(config.model).to(config.model_device)
  File "/data/sls/scratch/nmorgan/LOGIC/model_editing/malmen/model.py", line 41, in make_model
    model = AutoModelForFEVER(config.weight_path)
  File "/data/sls/scratch/nmorgan/LOGIC/model_editing/malmen/model.py", line 16, in __init__
    self.backbone = AutoModel.from_pretrained(name_or_path)
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 482, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1007, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/configuration_utils.py", line 620, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/data/sls/scratch/nmorgan/dotfiles/miniconda3/envs/logic-edits/lib/python3.10/site-packages/transformers/configuration_utils.py", line 708, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at '/data/sls/scratch/nmorgan/LOGIC/model_editing/malmen/model_files/bert_large_cased/pytorch_model.bin' is not a valid JSON file.
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.